import type {VisualScene} from "./types";

export const websiteOverviewScenes: VisualScene[] = [
  {
    id: "intro",
    kind: "intro",
    duration: 195,
    title: "Desert Technology Website Handover",
    body: "Customer Website + Business Management Dashboard",
    eyebrow: "Website overview showcase",
  },
  {
    id: "front-page",
    kind: "browser",
    duration: 260,
    image: "captures/storefront/home-hero.png",
    title: "A practical customer-facing website",
    caption: "A modern customer-facing website for technology products and services",
    callout: "Products, clear pricing, stock visibility, and direct local assistance",
    calloutX: 70,
    calloutY: 90,
  },
  {
    id: "categories",
    kind: "browser",
    duration: 230,
    image: "captures/storefront/home-categories.png",
    title: "Browse by category",
    caption: "Customers can quickly explore the technology range",
    callout: "Laptops, gaming, phones, desktops, accessories, and POS systems",
    calloutX: 95,
    calloutY: 90,
  },
  {
    id: "shop",
    kind: "browser",
    duration: 245,
    image: "captures/storefront/shop.png",
    title: "Product catalogue",
    caption: "Search and filters help customers find the right product",
    callout: "Products show condition, availability, price, and useful buying information",
    calloutX: 1020,
    calloutY: 90,
  },
  {
    id: "services",
    kind: "browser",
    duration: 230,
    image: "captures/storefront/services.png",
    title: "Technology and service support",
    caption: "The website presents both products and practical services",
    callout: "Security, networking, POS, auto services, and technology support",
    calloutX: 950,
    calloutY: 80,
  },
  {
    id: "promotions",
    kind: "browser",
    duration: 245,
    image: "captures/storefront/promotions.png",
    title: "Featured promotions",
    caption: "Active offers can be featured and updated from the dashboard",
    callout: "Promotions support both product offers and service campaigns",
    calloutX: 95,
    calloutY: 90,
  },
  {
    id: "contact",
    kind: "browser",
    duration: 215,
    image: "captures/storefront/contact.png",
    title: "Direct customer contact",
    caption: "Customers can reach Desert Technology by WhatsApp, call, or email",
    callout: "The website is designed to turn product interest into a direct conversation",
    calloutX: 960,
    calloutY: 90,
  },
  {
    id: "mobile",
    kind: "browser",
    duration: 200,
    image: "captures/storefront/home-mobile.png",
    title: "Responsive experience",
    caption: "The customer website remains clear and practical on mobile devices",
    callout: "Mobile-friendly browsing keeps products and contact actions close at hand",
    calloutX: 950,
    calloutY: 120,
    zoom: 0.82,
  },
  {
    id: "dashboard-section",
    kind: "section",
    duration: 180,
    eyebrow: "Behind the storefront",
    title: "One dashboard for daily business management",
    body: "Products, orders, documents, customers, promotions, users, and operational follow-ups are managed from one place.",
  },
  {
    id: "dashboard",
    kind: "browser",
    duration: 245,
    image: "captures/dashboard/overview.png",
    title: "Business overview",
    caption: "The dashboard gives the owner a clear view of store operations",
    callout: "Owner, Admin, and Staff roles help separate access responsibly",
    calloutX: 970,
    calloutY: 100,
  },
  {
    id: "dashboard-sections",
    kind: "browser",
    duration: 245,
    image: "captures/dashboard/products.png",
    title: "Control the customer-facing catalogue",
    caption: "Products, stock, categories, brands, and promotions stay connected",
    callout: "Updates made in the dashboard control what customers see on the website",
    calloutX: 960,
    calloutY: 90,
  },
  {
    id: "outro",
    kind: "outro",
    duration: 210,
    title: "Desert Technology Website Handover",
    body: "Training videos continue with step-by-step dashboard guides",
  },
];

export const dashboardOverviewScenes: VisualScene[] = [
  {
    id: "intro",
    kind: "intro",
    duration: 270,
    title: "Dashboard Overview",
    body: "How to sign in, understand the dashboard, and find each important section",
    eyebrow: "Training video 01",
  },
  {
    id: "login",
    kind: "section",
    duration: 420,
    eyebrow: "Step 1 · Secure access",
    title: "Sign in with your own dashboard account",
    body: "Open the staff sign-in page and use the account assigned to you. The Owner login should never be shared.",
  },
  {
    id: "overview",
    kind: "browser",
    duration: 600,
    image: "captures/dashboard/overview.png",
    title: "Dashboard home",
    caption: "The dashboard home gives a quick operational overview",
    callout: "Start here to review new orders, low-stock items, follow-ups, notifications, customers, and collected revenue",
    calloutX: 740,
    calloutY: 100,
  },
  {
    id: "navigation",
    kind: "browser",
    duration: 570,
    image: "captures/dashboard/overview.png",
    title: "Main navigation",
    caption: "Use the left sidebar to move between business areas",
    callout: "The sidebar keeps products, sales, customers, documents, users, and settings within easy reach",
    calloutX: 700,
    calloutY: 155,
    zoom: 1.07,
    panX: 80,
  },
  {
    id: "products",
    kind: "browser",
    duration: 600,
    image: "captures/dashboard/products.png",
    title: "Products",
    caption: "Manage catalogue items, pricing, stock, images, and website visibility",
    callout: "Use Products for daily catalogue and inventory work. Categories and Brands support customer filters.",
    calloutX: 880,
    calloutY: 90,
  },
  {
    id: "categories",
    kind: "browser",
    duration: 450,
    image: "captures/dashboard/categories-brands.png",
    title: "Categories and brands",
    caption: "Keep product organisation useful and customer-friendly",
    callout: "Consistent categories and brands make the storefront easier to browse",
    calloutX: 900,
    calloutY: 100,
  },
  {
    id: "orders",
    kind: "browser",
    duration: 600,
    image: "captures/dashboard/orders.png",
    title: "Orders, receipts, quotations, and payments",
    caption: "These sections support the complete sales and document workflow",
    callout: "Record sales, track payment status, and prepare downloadable business documents",
    calloutX: 880,
    calloutY: 90,
  },
  {
    id: "promotions",
    kind: "browser",
    duration: 450,
    image: "captures/dashboard/promotions.png",
    title: "Promotions",
    caption: "Create, feature, and arrange customer-facing offers",
    callout: "Featured promotions can appear prominently on the public website",
    calloutX: 900,
    calloutY: 100,
  },
  {
    id: "customers",
    kind: "browser",
    duration: 450,
    image: "captures/dashboard/customers.png",
    title: "Customers and follow-ups",
    caption: "Customer records support orders, documents, and ongoing service",
    callout: "Use only accurate customer information and protect private contact details",
    calloutX: 880,
    calloutY: 100,
  },
  {
    id: "users",
    kind: "browser",
    duration: 570,
    image: "captures/dashboard/users.png",
    title: "Users and roles",
    caption: "Owner, Admin, and Staff roles separate dashboard access",
    callout: "Invite each person with their own account. Do not share the Owner password.",
    calloutX: 850,
    calloutY: 100,
  },
  {
    id: "settings",
    kind: "browser",
    duration: 540,
    image: "captures/dashboard/settings.png",
    title: "Store settings and profile",
    caption: "Important business details and branding are managed here",
    callout: "Change technical or security-sensitive settings only with confirmed support",
    calloutX: 870,
    calloutY: 100,
  },
  {
    id: "audit",
    kind: "browser",
    duration: 540,
    image: "captures/dashboard/audit-log.png",
    title: "Notifications, follow-ups, and activity logs",
    caption: "These areas help the owner monitor daily work and important actions",
    callout: "Activity logs provide a readable record of important dashboard changes",
    calloutX: 880,
    calloutY: 100,
  },
  {
    id: "routine",
    kind: "section",
    duration: 450,
    eyebrow: "Daily starting point",
    title: "Review, update, then confirm the customer-facing result",
    body: "Check notifications and stock, complete operational work, and preview the website or document after important updates.",
  },
  {
    id: "outro",
    kind: "outro",
    duration: 270,
    title: "Dashboard Overview",
    body: "The next training video explains product management step by step.",
  },
];

export const totalFrames = (scenes: VisualScene[], transitionFrames = 15) =>
  scenes.reduce((sum, scene) => sum + scene.duration, 0) - (scenes.length - 1) * transitionFrames;
